name: Continuous Integration

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  cancel_previous:
    name: Cancel previous redundant builds
    runs-on: ubuntu-22.04
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    needs: cancel_previous
    name: Build app
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies and build
        run: |
          bun install
          bun run build
